---
inherit_from:
  - .niftany/layout.yml
  - .niftany/lint.yml
  - .niftany/metrics.yml
  - .niftany/naming.yml
  - .niftany/niftany_rubocop_rspec.yml
  - .niftany/performance.yml
  - .niftany/style.yml
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable

Metrics/ClassLength:
  Exclude:
    - 'lib/psu_identity/directory_service/person.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'psu_identity.gemspec'
